on: 
    push:
        branches:
            - main

jobs:
    build-and-test:
        name: build the codebase and run tests
        runs-on:
            ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Compile the tests
              run: make test
            - name: Run the tests
              run: ./test/TestMemoryPool && ./test/TestHashTable

